### ISSUE TITLE
[FE] MY_FR005_명함 넣은 기업 리스트(6h)

### ISSUE THREAD

**Issue by erirumble** [codestates-seb/seb44_main_015#13]
## 📌Feature Description

> 마이페이지-프리랜서에서 명함을 넣은 기업들의 리스트를 보여준다.

## ✨ To-do

- [x] 명함 넣은 회사리스트를 렌더링한다.
- [x] 각각의 리스트에는 회사 이름, 간단한 주소(ex:서울), D-day 등이 보여야한다.
- [x] 좌우스크롤을 추가하여 최대 N개 까지 회사리스트를 렌더링한다. N개는 추후 논의.

## ✍Additional context

> 추가설명

**Comment by ujujungbuck** [comment]
- [ ] N개 논의필요
