### ISSUE TITLE
[FE] MY_FR006_북마크한 채용(6h)

### ISSUE THREAD

**Issue by erirumble** [codestates-seb/seb44_main_015#14]
## 📌Feature Description

> 마이페이지-프리렌서에서 북마크 한 채용들의 리스트를 보여준다.

## ✨ To-do

- [x] 북마크한 회사리스트를 렌더링한다.
- [x] 각각의 리스트에는 회사 이름, 간단 주소, D-day등이 포함되어야 한다.
- [ ] 좌우스크롤을 추가하여 최대 N개 까지 볼 수 있게 한다.

## ✍Additional context

> 추가설명
