### ISSUE TITLE
[FE] CF001_헤더(3h)

### ISSUE THREAD

**Issue by heoh06** [codestates-seb/seb44_main_015#2]
## 📌Feature Description

> 화면 공통에 들어가는 헤더

## ✨ To-do

- [x] 홈페이지와 연결된 h1 로고
- [x] 카테고리 : 채용, 개발진
- [ ] 우측 : 비로그인 시 : 회원가입, 로그인 버튼
- [ ] 우측 : 로그인 시 : 프로필 호버 시 툴팁이 뜬다 [ 마이페이지, 로그아웃] 제공

## ✍Additional context

> 채용만 있으면 외로울 것 같아서 개발진을 카테고리에 넣었습니다. 페이지는 시간 나면 만들고자 일단 넣었습니다.
