### ISSUE TITLE
[FE] EP002_채용 리스트(5h)

### ISSUE THREAD

**Issue by heoh06** [codestates-seb/seb44_main_015#20]
/## 📌Feature Description

> 회사 채용 리스트들

## ✨ To-do

- [x] 컴포넌트 : 제목, 회사 이름, 회사 주소, 태그
- [ ] 페이징  : 무한 스크롤
- [x] 2단계 : 상위 카테고리 해당 태그 클릭 시  연관된 채용 공고만 나열  

## ✍Additional context

> 추가설명
