### ISSUE TITLE
[FE] MY_CO005_열린채용(4h)

### ISSUE THREAD

**Issue by erirumble** [codestates-seb/seb44_main_015#22]
## 📌Feature Description

> 마이페이지-회사에서 열린 채용을 보여준다.

## ✨ To-do

- [x] 열린 채용의 리스트를 보여준다.
- [x] 열른 채용 카드에는 채용글 제목과 '받은 명함 확인' 버튼이 위치한다.
- [x] '받은 명함 확인' 버튼을 누르면 명함리스트 페이지로 이동한다.
- [x] 좌우스크롤을 추가하여 열린 채용 리스트를 최대 N개까지 볼 수 있게 한다.

## ✍Additional context

> 추가설명
