### ISSUE TITLE
[FE] EP003_채용상세(6h)

### ISSUE THREAD

**Issue by heoh06** [codestates-seb/seb44_main_015#23]
## 📌Feature Description

> 회사가 낸 채용 상세 페이지

## ✨ To-do

- [ ] 채용글 제목, 태그
- [ ] 회사 정보: 회사 이름, 회사 주소, 인사 담당자 전화번호, 메일
- [ ] 회사 이미지 랜덤으로 라이브러리 찾아서 넣기
- [ ] 사용자 명함
- [ ] 명함 넣기 버튼
- [ ] 북마크 버튼
