### ISSUE TITLE
[FE] MY_CO006_지난 채용(4h)

### ISSUE THREAD

**Issue by erirumble** [codestates-seb/seb44_main_015#24]
## 📌Feature Description

> 마이페이지-회사에서 지난 채용 리스트를 보여준다.

## ✨ To-do

- [x] 지난 채용 리스트를 보여준다.
- [x] 지난 채용 카드에는 제목만 보여준다.-> disabledbutton으로 구현
- [x] 좌우스크롤을 추가해서 최대 N개까지 볼 수 있게 한다.

## ✍Additional context

> 추가설명
