### ISSUE TITLE
[FE] EP004_명함넣기(4h)

### ISSUE THREAD

**Issue by heoh06** [codestates-seb/seb44_main_015#25]
## 📌Feature Description

> 채용 상세 페이지에서 명함 넣기 버튼 클릭 시 이벤트

## ✨ To-do

- [ ] 현재 프리랜서 명함: 이름, 이메일, 전화번호, 태그, 이력 등이 전달됨
- [ ] 명함 넣기 버튼 클릭 시 [정말로 넣으시겠습니까?]와 같은 모달창 등장(디자인 참고)
- [ ] response로 OK가 왔을 때 명함 넣기 비활성화
- [ ] response fail 시 [Error] 토스트 알림(디자인 참고)

## ✍Additional context

> 토스트 기능은 추후에 추가여부 결정.
