### ISSUE TITLE
[FE] MY_CO007_받은 명함 리스트 상세 페이지(4h)

### ISSUE THREAD

**Issue by erirumble** [codestates-seb/seb44_main_015#27]
## 📌Feature Description

> 마이페이지-회사-받은 명함 리스트에서 받은 명함 리스트를 보여준다.

## ✨ To-do

- [x] 해당 채용에서 받은 명함들의 리스트를 보여준다.
- [x] 마이페이지에 있는 명함과 동일한 컴포넌트를 사용한다.
- [x] 명함 카드 안 우측 상단에 '더보기'버튼을 누르면 '명함 상세 페이지'로 이동한다.

## ✍Additional context

> 무한스크롤은 채용리스트에서 참고하기!
