### ISSUE TITLE
[FE] MY_FR001_명함(5h)

### ISSUE THREAD

**Issue by erirumble** [codestates-seb/seb44_main_015#3]
## 📌Feature Description

> 마이페이지-프리랜서에 있는 명함 부분입니다.

## ✨ To-do

- [x] 회원가입 시에 입력한 정보가 초기값으로 설정된다.
- [x] 태그 : 명함 상단에 n개를 보여준다. n의 값은 아직 미정.
- [x] 이름 : 태그 하단에 이름을 보여준다.
- [x] 이메일 : 이름 하단에 이메일을 보여준다.
- [x] 휴대폰 번호 : 이메일 하단에 휴대폰 번호를 보여준다.
- [ ] 수정 버튼 : 명함 우측하단 위치, 수정 버튼을 눌러서 수정 가능하게 한다.

## ✍Additional context

> 추가설명
