### ISSUE TITLE
[FE] MEM007_로그인(6h)

### ISSUE THREAD

**Issue by erirumble** [codestates-seb/seb44_main_015#31]
## 📌Feature Description

> 로그인페이지

## ✨ To-do

- [ ] 프리랜서와 회사 중 타입을 선택한다.
- [ ] email : 등록된 이메일이어야 한다. 아닐시에 입력칸 밑에 오류메세지를 출력한다.
- [ ] 로그인 성공 시 메인페이지로 이동시킨다.
- [ ] 로그인 버튼 밑에 회원가입 버튼을 추가한다.

## ✍Additional context

> 추가설명
