### ISSUE TITLE
[FE] MEM005, MEM006_회원가입-프리랜서 추가정보(6h)

### ISSUE THREAD

**Issue by ujujungbuck** [codestates-seb/seb44_main_015#32]
## 📌Feature Description

> 프리랜서가 본인의 산업군, 기술 스택, 특징등을 태그로 선택하여 추가정보를 기입하는 페이지

## ✨ To-do

- [ ] 인풋창을 감쌀 전체 박스 구현 : 전체 화면에서 중앙에 위치, 제목은 왼쪽정렬, 태두리 둥글게 구현(피그마참조)
- [ ] 산업군 : 산업군 제목 생성
- [ ] 개발자 : 산업군 아래에 개발자 제목 생성
- [ ] 개발자 태그들 나열칸 생성 : 프론트엔드, 백엔드 등 각 태그 박스 피그마 참조
- [ ] 디자이너 : 디자이너 제목 생성
- [ ] 디자이너 태그들 나열칸 생성 : UX디자이너 등 각 태그 박스 피그마 참조
- [ ] 번역가 : 번역가 제목 생성
- [ ] 번역가 태그들 나열칸 생성 : 영어, 일본어 등 각 태그 박스 피그마 참조
- [ ] 프리랜서 특징 : 프리랜서 특징 제목 생성
- [ ] 프리랜서 특징 태그들 나열칸 생성 : 재택희망, 다년간경력 등 각 태그 박스
- [ ] 태그 컴포넌트 API적용 : 만든 태그에 태그 API적용하여 GET으로 정보 받아오기
- [ ] 다음 : 다음버튼 생성하여 클릭하면 선택된 태그만 POST로 정보 보내기
- [ ] 회원가입 성공시 알림창 생성('회원가입 성공!')하고 로그인페이지로 리다이렉트하기

## ✍Additional context

> 컴포넌트 UI적으로 구현후 서버 구현완료되면 API통신 예정
