### ISSUE TITLE
[BE] MEM001, MEM004_회원가입-회사

### ISSUE THREAD

**Issue by nkower** [codestates-seb/seb44_main_015#37]
## 📌Feature Description
>  회사 회원가입시 기본정보를 입력

## ✨ To-do
- [ ] POST 요청으로 받아와야함
- [ ] 직접 가입시 회사 이름, 이메일, 패스워드, 휴대폰 번호, 회사 소개, 회사 주소, 산업군, 회사 특징의 정보를 받을 수 있어야함
- [ ] Oauth2 회원가입 시 이메일, 패스워드를 제외한 정보를 받을 수 있어야함

## ✍Additional context
>
