### ISSUE TITLE
[BE] MEM003, MEM005_회원가입-프리랜서 

### ISSUE THREAD

**Issue by nkower** [codestates-seb/seb44_main_015#40]
## 📌Feature Description

> 프리랜서 회원가입시 기본정보를 입력

## ✨ To-do

- [x] POST 요청으로 받아와야함
- [x] 직접 가입시 이름, 이메일, 패스워드, 휴대폰 번호, 산업군, 프리랜서 스펙 등의 정보를 받을 수 있어야함
- [ ] Oauth2 회원가입 시 이메일, 패스워드를 제외한 정보를 받을 수 있어야함

## ✍Additional context

> Oauth2는 여유가 있을때 구현
