### ISSUE TITLE
[BE] MEM007_로그인

### ISSUE THREAD

**Issue by nkower** [codestates-seb/seb44_main_015#42]
## 📌Feature Description

> JWT를 이용한 로그인

## ✨ To-do

- [x] 프리랜서, 회사 타입과 email, password를 받아와서 로그인 시도
- [x] 성공시 access토큰과 refresh토큰을 반환
- [ ] 성공시 유저의 DB에 refresh토큰을 저장
- [ ] Oauth2를 사용할 시 프리랜서, 회사 타입을 정하는 페이지를 따로 만들어야함

## ✍Additional context

> Oauth2를 사용할 경우 Oauth2 로그인 성공 -> 프리랜서, 회사 타입 선택 -> 없는 계정이라면 회원가입 과 같은 흐름으로 작동
