### ISSUE TITLE
[FE] MY_FR003_이력서(5h)

### ISSUE THREAD

**Issue by erirumble** [codestates-seb/seb44_main_015#7]
## 📌Feature Description

> 마이페이지-프리랜서에서 이력서 부분입니다.

## ✨ To-do

- [ ] 이력 추가 기능
- [ ] 이력 수정 기능
- [ ] 이력 삭제 기능

## ✍Additional context

> 추가설명
