### ISSUE TITLE
[FE] MEM003_회원가입-프리랜서 기본정보(4h)

### ISSUE THREAD

**Issue by ujujungbuck** [codestates-seb/seb44_main_015#8]
## 📌Feature Description

> 프리랜서가 회원가입시 기본정보를 입력하는 페이지

## ✨ To-do

- [ ] 인풋창을 감쌀 전체 박스 구현 : 전체 화면에서 중앙에 위치, 박스 안 상단에 '프리해요' 서비스명 위치, 테두리 둥글게 구현(후에 피그마참조)
- [ ] userType : Company와 Freelancer 선택을 버튼타입으로 작성
- [ ] 이름 : 이름인풋창 생성, 직접입력방식
- [ ] 이메일 : 이메일인풋창 생성, 직접입력방식 ('이메일 형식으로 작성하세요'를 placeholder나 메시지(인풋창 아래 작게 빨간색 글씨)로 알림)
- [ ] 비밀번호 : 비밀번호인풋창 생성 ('영문, 숫자, 특수문자 조합의 8자리 문자로 입력하세요'를 placeholder나 메시지로 알림)
- [ ] 휴대폰 번호 : 휴대폰번호 인풋창 생성 ('010-xxxx-xxxx으로 작성하세요'를 placeholder나 메시지로 알림)
- [ ] 동의 : '동의 후 회원가입이 가능합니다' 메시지 옆에 체크박스 생성
- [ ] 다음 : 다음버튼 생성, 클릭해야 추가정보 페이지로 이동
- [ ] 인풋 내용을 setState등으로 프론트에서 저장
- [ ] 인풋 내용을 서버에 axios POST요청
- [ ] 응답 OK가 아닐 경우 알림창('재입력해주세요') 생성

## ✍Additional context

> 컴포넌트 UI적으로 구현후 서버 구현되면 API통신 예정
